config/routes.rb
Rails.application.routes.draw do
  # get 'neurolinks/new'
  # get 'neurolinks/create'
  # get 'dreams/index'
  # get 'dreams/new'
  # get 'dreams/create'


  resources :dreams do
    resources :neurolinks, only: [:new, :create]
  end

  devise_for :escapists, controllers: { registrations: "escapists/registrations", sessions: "escapists/sessions" }
  root to: 'pages#home'

  get "neurolink/confirmation/:id", to: "neurolinks#confirmation", as: :neurolink_confirmation
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard', to: "dashboard#show", as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/dream.rb
class Dream < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :escapist

  validates :title, uniqueness: true, presence: true, length: { maximum: 13 }
  validates :category, presence: true, inclusion: { in: ["Daydream", "Lucid Dream", "Nightmare", "Prophetic Dream", "Epic Dream", "False Awakenings?", "Sexual Dream", "Deja vu Dream", "Clairvoyant Dream"] }

  validates :price, presence: true
end

app/models/escapist.rb
class Escapist < ApplicationRecord
  has_many :dreams, dependent: :destroy
  has_many :neurolinks, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/neurolink.rb
class Neurolink < ApplicationRecord
  belongs_to :dream
  belongs_to :escapist
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# class CategoriesController < ApplicationController
#   def show
#     @category = Dream.find_by category:
#   end
# end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @neurolinks = Neurolink.where(escapist: current_escapist) if current_escapist.neurolinks.any?
    @dreams = Dream.where(escapist: current_escapist) if current_escapist.dreams.any?
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :set_dream, only: [:show, :edit, :update, :destroy, :confirmation]

  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR category ILIKE :query"
      @dreams = Dream.where(sql_query, query: "%#{params[:query]}%")
    else
      @dreams = Dream.all
    end
  end

  def show
    @neurolink = Neurolink.new
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_strong_params)
    @dream.escapist = current_escapist
    if @dream.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @dream.update(dream_strong_params)
      redirect_to @dream, notice: 'dream is revised, continue to the matrix'
    else
      render :new
    end
  end

  def destroy
    @dream.destroy
    redirect_to dreams_path, notice: "dream is out of the matrix"
  end

  private

  def set_dream
    @dream = Dream.find(params[:id])
  end

  def dream_strong_params
    params.require(:dream).permit(:title, :price, :category, :description, :photo)
  end
end

app/controllers/escapists/registrations_controller.rb
class Escapists::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/dreams' # Or :prefix_to_your_route
  end
end

app/controllers/escapists/sessions_controller.rb
class Escapists::SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    '/dreams' # Or :prefix_to_your_route
  end
end

app/controllers/neurolinks_controller.rb
class NeurolinksController < ApplicationController
  # def new
  #   @dream = Dream.find(params[:dream_id])
  #   @neurolink = Neurolink.new
  # end

  def create
    @neurolink = Neurolink.new(neurolinks_strong_parameters)
    @dream = Dream.find(params[:dream_id])
    @neurolink.dream = @dream
    @neurolink.price = @dream.price
    @neurolink.escapist = current_escapist
    if @neurolink.save
      redirect_to neurolink_confirmation_path(@neurolink)
    else
      render :new
    end
  end

  def confirmation
    @neurolink = Neurolink.find(params[:id])
    @dream = @neurolink.dream
  end

  private

  def neurolinks_strong_parameters
    params.require(:neurolink).permit(:date, :escapist_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<div class="back">
  <%= link_to dreams_path, id: "back1" do %>
    <i class="fas fa-long-arrow-alt-left" style="font-size: 33px"></i>
  <% end %>
</div>

<div style="margin-right: 90px;">
<div class="container" id="dash">

  <h1 id="dreamboard" style="font-weight: bold; color: #FA2EF5;">Dreamboard</h1>
 <%= link_to "Sign out", destroy_escapist_session_path, method: :delete, data: {confirm: "Are you sure you want to log out?"} %>
  <br>
  <br>
  <br>
  <br>
  <h2 style="font-size: 21px">Neurolinks</h2>
  <br>




    <div class="cards">
      <% if @neurolinks.nil? %>
        <div class="card" style="background-image: linear-gradient((255,255,255,0.7), (255,255,255,0.7)), url(https://il3.picdn.net/shutterstock/videos/2313281/thumb/1.jpg)">
          <div class="card-content">
            <p style="color: #CCCCCC; font-size: 33px">You have no Neurolinks yet.</p>
          </div>
        </div>
      <% else %>
        <% @neurolinks.each do |n| %>
          <% url = n.dream.photo.file.nil? ? image_url("brain.svg") : cl_image_path(n.dream.photo) %>
          <%= link_to '#' do %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url('https://il3.picdn.net/shutterstock/videos/2313281/thumb/1.jpg')">
              <div class="card-content">
                <h1><strong><%= n.dream.title  %></strong> </h1>
                <p><%= n.date %></p>
                <p style="font-size: 33px">$<%= n.dream.price %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>

    </div>
  <br>
  <br>


  <br>
  <h2 style="font-size: 21px">Dreams</h2>
 <br>
  <div class="cards">
      <% if @dreams.nil? %>

        <div class="card" style="background-image: linear-gradient((255,255,255,0.7), (255,255,255,0.7)), url(https://il3.picdn.net/shutterstock/videos/2313281/thumb/1.jpg)">
          <div class="card-content">
            <p style="color: #CCCCCC; font-size: 33px;">You have no dreams yet.</p>
          </div>
        </div>

      <% else %>



        <% @dreams.each do |d| %>
          <% url = d.photo.file.nil? ? image_url("brain.svg") : cl_image_path(d.photo) %>
          <%= link_to dream_path(d.id) do %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url('<% url %>')">
              <div class="card-content">
                <h1><strong><%= d.title  %></strong> </h1>

                <p style="font-size: 33px">$<%= d.price %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>

  </div>



    <br><br>

      <% if escapist_signed_in? %>
        <%= link_to 'Create dream', new_dream_path, class: "btn" %>
      <% else %>
        <%= link_to 'Create dream', new_escapist_session_path, class: "btn" %>
      <% end %>

</div>
</div>

<br><br><br><br>

app/views/dreams/_form.html.erb
<div class="container">
  <%= simple_form_for @dream do |f| %>

  <div class="form-group">
     <%= f.input :title , class: "form-control" %>
  </div>

  <div class="form-group row">
    <div class="col-xs-12 col-sm-8">
      <%= f.input :category, collection: ["Daydream", "Lucid Dream", "Nightmare", "Prophetic Dream", "Epic Dream", "False Awakenings?", "Sexual Dream", "Deja vu Dream", "Clairvoyant Dream"], class: "form-control"%>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= f.input :price, class: "form-control" %>
    </div>
  </div>

 <div class="form-group">
    <%= f.input :description , class: "form-control"%>
</div>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <br>
  <%= f.button :submit, class: "btn btn-secondary" %>
</div>
<% end %>


</div>

app/views/dreams/edit.html.erb
<div class="back">
  <%= link_to dreams_path, id: "back1" do %>
    <i class="fas fa-long-arrow-alt-left" style="font-size: 33px"></i>
  <% end %>
</div>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <%= render 'form', dream: @dream %>
    </div>
  </div>
</div>

app/views/dreams/index.html.erb
<br>
<div style="margin-right: 90px;">
  <div class="container">
    <br>

    <!-- [search form] -->
    <%= form_tag dreams_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a dream"
      %>
    <% end %>



    <!-- the list of movies -->

    <br>



    <div class="cards">
      <% @dreams.each do |d| %>
        <% url = d.photo.file.nil? ? image_url("inception.png") : cl_image_path(d.photo) %>
          <%= link_to dream_path(d.id) do %>
          <div class="card" style=" background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url('<%= url %>')">
            <div class="card-content">
              <h1><strong><%= d.title  %></strong> </h1>
              <p><%= d.category %></p>
              <p style="font-size: 33px">$<%= d.price %></p>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
      <br>

  </div>

  <br>
  <br>
  <br>
  <div class="container">
    <h5 style="font-size: 13px; text-align: center; color: #FA2EF5;">Has the nightmare just begun?</h5>
  </div>
</div>
<br>
<br>
<br>

app/views/dreams/new.html.erb
<div class="back">
  <%= link_to dashboard_path, id: "back1" do %>
    <i class="fas fa-long-arrow-alt-left" style="font-size: 33px"></i>
  <% end %>
</div>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <%= render 'form', dream: @dream %>
    </div>
  </div>
</div>

app/views/dreams/show.html.erb
 <% url = @dream.photo.file.nil? ? image_url("inception.png") : cl_image_path(@dream.photo) %>
 <div class="banner" style="background-image: url('<%= url %>')">
</div>
<br>
<br>
<div class="container cont" style="width: 950px">
<%= link_to dreams_path, id: "back" do %>
  <i class="fas fa-long-arrow-alt-left" style="font-size: 33px"></i>
<% end %>
  <br>
    <div>
      <div class="d-flex justify-content-between">
        <h1 style="color: #FA2EF5; font-weight: lighter;"><strong><%= @dream.title %></strong></h1>
        <h1 style="font-size: 50px"><strong>$<%= @dream.price %></strong></h1>
      </div>
      <h5 style="font-weight: bold;"> <%= @dream.category %></h5>
      <br>
      <p> <%= @dream.description %></p>
    </div>
    <br>
    <br>


  <% if @dream.escapist == current_escapist %>
    <div class="d-flex">
      <%= link_to 'Edit', edit_dream_path(@dream), class: "btn" %>
      <%= link_to 'Destroy', @dream, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
    </div>
  <% else %>
    <div class="form-wrapper" style="width: auto; margin: 0 auto;">
      <%= simple_form_for [@dream, @neurolink] do |f| %>
        <!--  <div class="d-flex justify-content-between"> -->
          <%= f.input :date, as: :date, required: false, input_html: {class: "datepicker flex-fill"} %>
          <br>
        <!--</div> -->
        <% if escapist_signed_in? %>
          <%= f.button :submit, "Dream", class: "btn flex-fill mb-3" %>
        <% else %>
          <%= link_to 'Dream', new_escapist_session_path, class: "btn flex-fill" %>
        <% end %>

      <% end %>
    <% end %>
    <!--  </div> -->

  </div>

  <br>
  <br>
  <br>
</div>


<!-- <div class="w"> -->
      <%# if escapist_signed_in? %>
        <%#= link_to 'Edit', edit_dream_path(@dream), class: "btn flex-fill" %>
      <%# else %>
        <%#= link_to 'Edit', new_escapist_session_path, class: "btn flex-fill" %>
      <%# end %>

      <%# if escapist_signed_in? %>
        <%#= link_to 'Destroy', @dream, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn flex-fill" %>
      <%# else %>
        <%#= link_to 'Destroy', new_escapist_session_path, class: "btn flex-fill" %>
      <%# end %>
    <!-- <div class="container"> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Inception</title>
    <link rel="stylesheet" href="https://use.typekit.net/wtt0vuo.css">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <p class="alert"><%= alert %></p>

     <% if current_page?("http://localhost:3000/dreams/new") || current_page?("http://localhost:3000/escapists/sign_in") || current_page?("https://inceptionapp.herokuapp.com/dreams/new") || current_page?("https://inceptionapp.herokuapp.com/escapists/sign_in")%>
      <%= render "shared/footer" %>
      <% end %>
    <%= yield %>

    <% unless current_page?("http://localhost:3000/") || current_page?("https://inceptionapp.herokuapp.com/") || current_page?("http://localhost:3000/dreams/new") || current_page?("http://localhost:3000/escapists/sign_in") || current_page?("https://inceptionapp.herokuapp.com/escapists/sign_in") || current_page?("https://inceptionapp.herokuapp.com/dreams/new")%>
      <%= render "shared/navbar" %>
    <% end %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/neurolinks/_form.html.erb
<div class="container">
  <%= simple_form_for @dream do |f| %>

  <div class="form-group">
     <%= f.input :title , class: "form-control" %>
  </div>

  <div class="form-group row">
    <div class="col-xs-12 col-sm-8">
      <%= f.input :category, class: "form-control"%>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= f.input :price, class: "form-control" %>
    </div>
  </div>

 <div class="form-group">
    <%= f.input :description , class: "form-control",  rows: "7"%>
</div>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
</div>
<% end %>


</div>

app/views/neurolinks/confirmation.html.erb
<div class="back">
  <%= link_to dreams_path, id: "back1" do %>
    <i class="fas fa-long-arrow-alt-left" style="font-size: 33px"></i>
  <% end %>
</div>


<div class="container">
    <div id="typewriter2" class="d-flex justify-content-center">
     Your brain is successfully neurolinked!
    </div>
  </div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">

      <div class="d-flex justify-content-between">
        <h1 style="color: #FA2EF5"><strong><%= @dream.title %></strong></h1>
        <p style="font-size: 35px"><strong>$<%= @dream.price %></strong></p>
      </div>
      <div class="d-flex justify-content-between">
        <p style="font-size: 25px"><%= @dream.category %></p>
        <p style="font-size: 25px"><%= @neurolink.date %></p>
      </div>
      <br>
      <p> <%= @dream.description %></p>
      <br>
      <div class="d-flex">
        <%= link_to 'Home', dreams_path, class: "btn flex-fill mb-3" %>
        <%= link_to 'Dashboard', dashboard_path, class: "btn flex-fill mb-3" %>
      </div>
      <br>
    </div>
  </div>


</div>

app/views/pages/home.html.erb
 <div class="banner" style="background-image: url('<%= image_url("http://eeerik.com/apps/WhoRU/img/6.nightmare.gif") %> ')">
  <div class="container">
    <div id="typewriter" class="d-flex">
     the new technological era has arrived;
     humanity has reached neuroscientific advancements never known before;
     the world of fantasy, alternate universes and speculation is now our reality.
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to 'enter the multiverse', dreams_path, class: "btn home-btn", style: "width: 550px;" %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- <div class="footer" style="text-align: center; color:white;" > -->
  <!-- <div class="footer-links" >
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> -->
  <!-- style="background-color: #FA2EF5; color:white; height: 41px; border-color: #FA2EF5" -->
<div id="maindiv" class="border-right-0 border-left-0">
  <div id="div1">
    &nbsp;———— /////////// ————   ESCAPIST
     ———— /////////// ————   ESCAPIST
    ———— /////////// ————   ESCAPIST
    ———— /////////// ————   ESCAPIST
      ———— /////////// ————   ESCAPIST
    ———— /////////// ————   ESCAPIST
    ———— /////////// ————   ESCAPIST

  </div>
  <div id="div2">
    &nbsp;———— /////////// ————   ESCAPIST
     ———— /////////// ————   ESCAPIST
    ———— /////////// ————   ESCAPIST
    ———— /////////// ————   ESCAPIST
      ———— /////////// ————   ESCAPIST
    ———— /////////// ————   ESCAPIST
    ———— /////////// ————   ESCAPIST

  </div>
</div>
<!-- <div class="wrap"> -->




<!-- <span id="watchme">
  <span >———— /////////// ————&nbsp;&nbsp;&nbsp;Call 1-833-MAR-CIVE. Dial #000&nbsp;&nbsp;</span>
  <span >———— /////////// ————&nbsp;&nbsp;&nbsp;Call 1-833-MAR-CIVE. Dial #000&nbsp;&nbsp;</span>
  <span >———— /////////// ————&nbsp;&nbsp;&nbsp;Call 1-833-MAR-CIVE. Dial #000&nbsp;&nbsp;</span>
</span> -->

<!-- </div> -->
<!-- </div> -->

app/views/shared/_navbar.html.erb
<aside class="sidebar navbar-expand-sm navbar-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="sidebar_description">
    <%= link_to image_tag("inception.svg", :class => 'navbar-brand'), dreams_path %>
  </div>

  <div class="nav-link">
    <% if current_escapist.nil? %>
      <%= link_to new_escapist_session_path do %>
        <% image_tag "home.svg", id: "profile" %>
      <% end %>
    <% else %>
      <%= link_to dashboard_path do %>
        <% image_tag "home.svg", id: "profile" %>
      <% end %>
    <% end %>
  </div>
</div>


<!-- author thanks for the icon -->
<!--
<div>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"                 title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"                 title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div> -->